<?xml version="1.0" ?>
<!DOCTYPE note [
<!ELEMENT note  (to,from,heading,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>

<note>
<to>manuel</to>
<from>tyler</from>
<heading>reminder</reminder>
<body>party</body>


</note>